### ISSUE TITLE
Carbon UI shell with side nav is not built to work with Carbon's grid

### ISSUE THREAD

**Issue by mattrosno** [mattrosno/carbon-platform#4]
I'm using Carbon's HeaderContainer, Header, and SideNav. Because the SideNav is fixed positioned, the Carbon component Content by default renders full viewport width and under the SideNav.

I had to use my own `.content` class with:

```scss
@import "carbon-components/scss/globals/scss/layout";

.content {
  margin: 3rem 0 0 16rem;
  background: var(--cds-ui-background);

  @include carbon--breakpoint-down(lg) {
    margin-left: 0;
  }
}
```

Also, Carbon guidance talks about grid influencer when there's a left rail, but does not specify if there should be a 256px left influencer when using Carbon's default UI shell.
